#!/bin/sh

#RST PCA@21 (base = 324) + 7
echo 331 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio331/direction

#RST = 0
echo 0   > /sys/class/gpio/gpio331/value
#sleep 1
#RST = 1
echo 1   > /sys/class/gpio/gpio331/value

echo 331 > /sys/class/gpio/unexport
